<a href="https://colab.research.google.com/github/rutujahingankar/Play-store-app-review-analysis/blob/main/User_reviews_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <b> The Play Store apps data has enormous potential to drive app-making businesses to success. Actionable insights can be drawn for developers to work on and capture the Android market. </b>

## <b> Each app (row) has values for catergory, rating, size, and more. Another dataset contains customer reviews of the android apps.</b>

## <b> Explore and analyze the data to discover key factors responsible for app engagement and success. </b>

In [ ]:
#import library
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra
import matplotlib.pyplot as plt
import seaborn as sns  # visualization tool

In [ ]:
from google.colab import drive
drive.mount('/content/drive') # Mounted Google Drive

Mounted at /content/drive

In [ ]:
df =pd.read_csv('/content/drive/MyDrive/Play Store Data.csv')   # Read the Google play store Data
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [ ]:
df_review = pd.read_csv('/content/drive/MyDrive/User Reviews.csv') # Read the User Reviews
df_review.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

#**Analysis Of User Review Data**

In [ ]:
#Drop missing data
df_review.dropna(inplace= True)

In [ ]:
#Drop the column 
df_review.drop("Translated_Review",axis= 1, inplace= True)

In [ ]:
# Rename the remaining column 
df_review.columns = ["App", "Sentiment", "polarity", "subjectivity"]
df_review

                                  App Sentiment  polarity  subjectivity
0               10 Best Foods for You  Positive  1.000000      0.533333
1               10 Best Foods for You  Positive  0.250000      0.288462
3               10 Best Foods for You  Positive  0.400000      0.875000
4               10 Best Foods for You  Positive  1.000000      0.300000
5               10 Best Foods for You  Positive  1.000000      0.300000
...                               ...       ...       ...           ...
64222  Housing-Real Estate & Property  Positive  0.173333      0.486667
64223  Housing-Real Estate & Property  Positive  0.225000      0.447222
64226  Housing-Real Estate & Property  Negative -0.287500      0.250000
64227  Housing-Real Estate & Property  Positive  0.800000      1.000000
64230  Housing-Real Estate & Property  Negative -0.316667      0.400000

[37427 rows x 4 columns]

In [ ]:
#shape before removing duplicates
df_review.shape

(37427, 4)

In [ ]:
len(df_review[df_review.duplicated()])

12343

In [ ]:
#list of all duplicates values
duplicate_review = df_review[df_review.duplicated(keep = 'last')]
print(duplicate_review)

                                  App Sentiment  polarity  subjectivity
0               10 Best Foods for You  Positive      1.00      0.533333
1               10 Best Foods for You  Positive      0.25      0.288462
3               10 Best Foods for You  Positive      0.40      0.875000
4               10 Best Foods for You  Positive      1.00      0.300000
5               10 Best Foods for You  Positive      1.00      0.300000
...                               ...       ...       ...           ...
64179  Hotwire Hotel & Car Rental App   Neutral      0.00      0.000000
64188  Hotwire Hotel & Car Rental App   Neutral      0.00      0.000000
64199  Housing-Real Estate & Property  Negative     -0.50      0.200000
64200  Housing-Real Estate & Property   Neutral      0.00      0.000000
64205  Housing-Real Estate & Property   Neutral      0.00      0.000000

[12343 rows x 4 columns]

In [ ]:
#Remove duplicates and save as new DataFrame
df_new_reviews = df_review.drop_duplicates()
df_new_reviews.shape

(25084, 4)

In [ ]:
df_new_reviews.isnull().sum()

App             0
Sentiment       0
polarity        0
subjectivity    0
dtype: int64

In [ ]:
df_new_reviews.describe()

           polarity  subjectivity
count  25084.000000  25084.000000
mean       0.189794      0.538103
std        0.355776      0.220541
min       -1.000000      0.000000
25%        0.000000      0.403700
50%        0.189167      0.540000
75%        0.416667      0.666667
max        1.000000      1.000000